#!/bin/sh
set -euo pipefail

REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
SECRETS_FILE="$REPO_ROOT/Config/Secrets.xcconfig"

if [ -z "${NOBETECZA_API_KEY:-}" ]; then
  echo "warning: NOBETECZA_API_KEY is not set in Xcode Cloud workflow secrets."
  exit 0
fi

cat > "$SECRETS_FILE" <<EOF
// Generated by Xcode Cloud — do not commit
NOBETECZA_API_KEY = ${NOBETECZA_API_KEY}
EOF

echo "Wrote API key to Config/Secrets.xcconfig for CI build."
